### ISSUE TITLE
Inner classes/enums

### ISSUE THREAD

**Issue by Artur2** [Saritasa/SaritasaTools#18]
Need to move using static Saritasa.Tools.Common.Extensions.DateTimeTruncation.
Because with useful usage we must use code like this - 
`using static Saritasa.Tools.Common.Extensions.DateTimeExtensions;`
Move out from class and to file.
Is this possible or appropriate ?

**Comment by krasninja** [comment]
Fixed, will be released in version 0.1.3 .
