### ISSUE TITLE
ZergRushCo: Wrong e-mail validation

### ISSUE THREAD

**Issue by dermeister0** [Saritasa/SaritasaTools#21]
> User name test+1@example.com is invalid, can only contain letters or digits.

**Comment by Artur2** [comment]
@dermeister0 , you can use [this](https://referencesource.microsoft.com/#System.ComponentModel.DataAnnotations/DataAnnotations/EmailAddressAttribute.cs,54) regular expression to validate submitted email.

**Comment by krasninja** [comment]
Fixed.
