### ISSUE TITLE
BaseExecutorMiddleware should dispose resolved objects

### ISSUE THREAD

**Issue by dermeister0** [Saritasa/SaritasaTools#31]
The change is for internal resolver only.

- Dispose handlers after each *ExecuteHandler* call.
- Dispose method parameters after each *ExecuteHandler* call.

Alternatively, cache handlers and dispose them when middleware is disposed.

**Comment by dermeister0** [comment]
If external resolver is used, don't dispose the objects.

**Comment by krasninja** [comment]
Should be fixed in new release.
