### ISSUE TITLE
EFQueryableRepository does not support async operations

### ISSUE THREAD

**Issue by dermeister0** [Saritasa/SaritasaTools#35]
```
await userRepository.ToArrayAsync();
```

> InvalidOperationException: The source IQueryable doesn't implement IAsyncEnumerable<User>. Only sources that implement IAsyncEnumerable can be used for Entity Framework asynchronous operations.
Microsoft.EntityFrameworkCore.Extensions.Internal.QueryableExtensions.AsAsyncEnumerable<TSource>(IQueryable<TSource> source)

You should implement IAsyncEnumerableAccessor.
https://github.com/aspnet/EntityFramework/blob/dev/src/EFCore/DbSet%60.cs#L401

```
        /// <inheritdoc />
        public IAsyncEnumerable<TEntity> AsyncEnumerable => ((IAsyncEnumerableAccessor<TEntity>)set).AsyncEnumerable;
```

**Comment by krasninja** [comment]
Please try new version and let me know.
https://www.nuget.org/packages/Saritasa.Tools.EFCore1/0.2.2

**Comment by dermeister0** [comment]
It works.
