### ISSUE TITLE
BoringWarehouse - compilation error

### ISSUE THREAD

**Issue by dermeister0** [Saritasa/SaritasaTools#4]
Profile.cshtml uses UpdateUserCommand instead of UpdateUserProfileCommand.

> error CS1061: 'UpdateUserCommand' does not contain a definition for 'ConfirmPassword' and no extension method 'ConfirmPassword' accepting a first argument of type 'UpdateUserCommand' could be found (are you missing a using directive or an assembly reference?)

**Comment by Donil** [comment]
Fixed
