### ISSUE TITLE
Announcements

### ISSUE THREAD

**Issue by Artur2** [Saritasa/SaritasaTools#41]
Need to publish announcements related to breaking changes, for example after I merged dev branch in old
feature branch, code is broken, because some public part of framework changed.

For example here - asp.net team announcing breaking changes and ways to [migrate.](https://github.com/aspnet/Announcements)

**Comment by krasninja** [comment]
Right now project in active development and API may be changed frequently. When we stabilize it we will update version to 1.0.0 and would follow semver. All changes are described in release notes to nuget package.
