### ISSUE TITLE
DateTimeUtils Truncate method issue

### ISSUE THREAD

**Issue by ko-vasilev** [Saritasa/SaritasaTools#42]
DateTimeUtils.Truncate method works the same way for DateTimePeriod.Day and DateTimePeriod.Month values (those enums even have the same comments associated).
From the looks of it, we need to remove the DateTimePeriod.Month, or remove the DateTimePeriod.Year because it looks like .Month should do what .Year currently does

**Comment by krasninja** [comment]
It is fixed: https://www.nuget.org/packages/Saritasa.Tools.Common/0.4.0 . Not it should work in this way: https://www.postgresql.org/docs/9.5/static/functions-datetime.html#FUNCTIONS-DATETIME-TRUNC

**Comment by ko-vasilev** [comment]
I'm not sure why did you make "Millisecond" option for Truncate to not modify the original DateTime. There is a constructor that takes millisecond as parameter as well as DateTimeKind.

**Comment by krasninja** [comment]
Will be fixed in next release.

**Comment by krasninja** [comment]
Fixed.
