### ISSUE TITLE
Remove SortOrder enum, use System.ComponentModel.ListSortDirection

### ISSUE THREAD

**Issue by dermeister0** [Saritasa/SaritasaTools#44]
https://github.com/Saritasa/SaritasaTools/blob/fb247f15a449f280260d179ffe2fcdff1ce73969/src/Saritasa.Tools.Common/Utils/SortOrder.cs#L4

https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.listsortdirection?view=netframework-4.7.1

**Comment by krasninja** [comment]
It seems it is not available for .net standard < 2.0 : https://docs.microsoft.com/ru-ru/dotnet/api/system.componentmodel.listsortdirection?view=netframework-4.7.1&viewFallbackFrom=netstandard-1.6

In this case we have to limit to .net standard 2.0 (or make shim).

**Comment by krasninja** [comment]
Planned for next release:
https://github.com/Saritasa/SaritasaTools/commit/a02876ea901e9ff14fdc7fcacfd256d79de03de2
