### ISSUE TITLE
Saritasa.RulesetInstall.ps1 creates too many CodeAnalysisRuleSet elements

### ISSUE THREAD

**Issue by dermeister0** [Saritasa/SaritasaTools#45]
![2018-02-15_1726](https://user-images.githubusercontent.com/4054844/36292141-1afe392c-1302-11e8-99e7-260cac98ae53.png)

Proposed solution:
- Remove all CodeAnalysisRuleSet elements;
- Add CodeAnalysisRuleSet to the first PropertyGroup without Condition.

**Comment by krasninja** [comment]
Fixed: https://github.com/Saritasa/SaritasaTools/blob/develop/scripts/Saritasa.RulesetInstall.ps1
