### ISSUE TITLE
Change exception type when command is null

### ISSUE THREAD

**Issue by dermeister0** [Saritasa/SaritasaTools#47]
Message pipeline throws ArgumentNullException when command is null.

> System.ArgumentNullException: Value cannot be null.
> Parameter name: command
>    at Saritasa.Tools.Messages.Commands.CommandPipeline.CreateMessageContext(IMessagePipelineService pipelineService, Object command)
>   at Saritasa.Tools.Messages.Abstractions.MessagePipelineServiceExtensions.<HandleCommandAsync>d__3.MoveNext()

Is it possible to throw `MessageProcessingException` instead? I need something like `CommandValidationMiddleware` to validate null commands.

**Comment by krasninja** [comment]
I'm thinking to move message context formatting into separate middleware. This would make pipeline move flexible and you can override this behavior.
