### ISSUE TITLE
ArgumentNullException in StringUtils.ParseOrDefault

### ISSUE THREAD

**Issue by AntonZiminSaritasa** [Saritasa/SaritasaTools#74]
```
StringUtils.ParseOrDefault<int>(null, 0)
```

**Comment by AntonZiminSaritasa** [comment]
Actually, it throws another exception:
```
Unhandled exception. System.ArgumentException: Type provided must be an Enum.
```

I'm using it incorrectly. Correct usage:

```
StringUtils.ParseOrDefault(null, 0)
```

**Comment by krasninja** [comment]
You are right, but I do believe that the `StringUtils.ParseOrDefault<int>` form is still valid. I will update the lib to handle these calls using fallback methods.
